# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: atom_server.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x61tom_server.proto\"8\n\nPatternMsg\x12\x11\n\tatomspace\x18\x01 \x01(\t\x12\x17\n\x05query\x18\x02 \x01(\x0b\x32\x08.LinkMsg\"%\n\x07NodeMsg\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\"3\n\x07LinkMsg\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x1a\n\x08outgoing\x18\x02 \x03(\x0b\x32\x08.AtomMsg\"E\n\x07\x41tomMsg\x12\x18\n\x04link\x18\x01 \x01(\x0b\x32\x08.LinkMsgH\x00\x12\x18\n\x04node\x18\x02 \x01(\x0b\x32\x08.NodeMsgH\x00\x42\x06\n\x04\x61tom\"8\n\x0b\x41tomRequest\x12\x11\n\tatomspace\x18\x01 \x01(\t\x12\x16\n\x04\x61tom\x18\x02 \x01(\x0b\x32\x08.NodeMsg2\xa9\x01\n\nAtomServer\x12)\n\x0e\x45xecutePattern\x12\x0b.PatternMsg\x1a\x08.AtomMsg0\x01\x12#\n\tCheckNode\x12\x0c.AtomRequest\x1a\x08.NodeMsg\x12\'\n\x0b\x46indSimilar\x12\x0c.AtomRequest\x1a\x08.NodeMsg0\x01\x12\"\n\x08\x46indType\x12\x0c.AtomRequest\x1a\x08.NodeMsgb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'atom_server_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_PATTERNMSG']._serialized_start=21
  _globals['_PATTERNMSG']._serialized_end=77
  _globals['_NODEMSG']._serialized_start=79
  _globals['_NODEMSG']._serialized_end=116
  _globals['_LINKMSG']._serialized_start=118
  _globals['_LINKMSG']._serialized_end=169
  _globals['_ATOMMSG']._serialized_start=171
  _globals['_ATOMMSG']._serialized_end=240
  _globals['_ATOMREQUEST']._serialized_start=242
  _globals['_ATOMREQUEST']._serialized_end=298
  _globals['_ATOMSERVER']._serialized_start=301
  _globals['_ATOMSERVER']._serialized_end=470
# @@protoc_insertion_point(module_scope)
